### ISSUE TITLE
Integrate Firebase Services 

### ISSUE THREAD

**Issue by vaibhavchellani** [GDGBVCOE/NoQueue#1]
Integrate the following services provided by firebase 

- Authentication

- Realtime Database

- Crash Reporting 

- Analytics

**Comment by Jasmeet1709** [comment]
done

**Comment by vaibhavchellani** [comment]
great , but for further issues please comment on the issue before working on it , so that no one else starts working on it .

**Comment by vaibhavchellani** [comment]
add 

- fcm too

**Comment by vaibhavchellani** [comment]
this is done in issue #5
