### ISSUE TITLE
User part (Join Queue)

### ISSUE THREAD

**Issue by Jasmeet1709** [GDGBVCOE/NoQueue#12]

**Comment by Jasmeet1709** [comment]
@vaibhavchellani I am doing this if you are not doing this.

**Comment by vaibhavchellani** [comment]
@Jasmeet1709  ill be pushing the code latest by tonight , please start working after that , have you pulled the current code

**Comment by Jasmeet1709** [comment]
@vaibhavchellani yup

**Comment by vaibhavchellani** [comment]
@Jasmeet1709 this issue has been resolved in commit beeab9349bb074117306440ba853e8d083ccc752

Hence closing now , assigning other issue
