### ISSUE TITLE
User Interface of adding new Queue activity

### ISSUE THREAD

**Issue by ghost** [GDGBVCOE/NoQueue#16]
button and edit fields edit

**Comment by vaibhavchellani** [comment]
okay @IshaAgarwal98  you can work on this issue and create a PR

**Comment by vaibhavchellani** [comment]
let me know if you need some info regarding this

**Comment by vaibhavchellani** [comment]
@IshaAgarwal98  @YashishDua  we need more work to close this issue . Lets get to it

**Comment by ghost** [comment]
till Friday I will make the ui of the 3 screens

**Comment by ghost** [comment]
then only the main screen will be left

**Comment by vaibhavchellani** [comment]
@IshaAgarwal98 Great !

**Comment by YashishDua** [comment]
I'll improve this screen.

**Comment by vaibhavchellani** [comment]
@YashishDua  this issue has been resolved , please make an issue with title ,"improving CreateQueue Laout " for improvements to this screen ,
