### ISSUE TITLE
submit email IDS so that i can provide you firebase access 

### ISSUE THREAD

**Issue by vaibhavchellani** [GDGBVCOE/NoQueue#2]

**Comment by Mridul97** [comment]
mridulaggarwal97@gmail.com

**Comment by Rikki407** [comment]
rishablamba407@gmail.com

**Comment by Jasmeet1709** [comment]
jsmtbagga45@gmail.com

**Comment by ghost** [comment]
Ishagar98@gmail.com

**Comment by vaibhavchellani** [comment]
@IshaAgarwal98 @Jasmeet1709 @Rikki407 @Mridul97 check your inbox for firebase invite and accept it

**Comment by vaibhavchellani** [comment]
Closing this issue
