### ISSUE TITLE
Adding onClick Listener on the Recycler List View

### ISSUE THREAD

**Issue by Jasmeet1709** [GDGBVCOE/NoQueue#28]
@vaibhavchellani i am working on this

**Comment by vaibhavchellani** [comment]
@Jasmeet1709 sure go ahead !

**Comment by jaykishan007** [comment]
I would like to work on it, is it done or yet to be?

**Comment by vaibhavchellani** [comment]
@jaykishan007 we have already started working on this one , feel free to create a new issue to work on it , we will be making changes in the codebase to make it more friendly for developers and add contributing guidelines too
