### ISSUE TITLE
Create Realtime database structure 

### ISSUE THREAD

**Issue by vaibhavchellani** [GDGBVCOE/NoQueue#4]

**Comment by vaibhavchellani** [comment]
@Jasmeet1709 @Rikki407 please suggest a structure as soon as possible , post screenshots here and we can discuss .

**Comment by Rikki407** [comment]
I will .....just give me time till tomorrow night

**Comment by vaibhavchellani** [comment]
@Rikki407 sure ! 
please make sure the structure is  as flat as it can be .

**Comment by vaibhavchellani** [comment]
@Rikki407 have a look at the structure we have created , and let us know if you feel some improvements can be made , let me know if you need more explanation .

**Comment by vaibhavchellani** [comment]
done in latest commit beeab9349bb074117306440ba853e8d083ccc752
